"""spAlignDE public Python interface."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import anndata as ad

__version__ = "0.1.0"

from .alignment import (
    ATACSTAlignmentConfig,
    ATACSTAlignmentResult,
    ATACSTPrealignmentConfig,
    ATACSTPrealignmentResult,
    AllenCCFReference,
    CrossSampleAlignmentResult,
    CrossSampleFields,
    ManualPrealignmentConfig,
    ManualPrealignmentUI,
    PrealignmentConfig,
    PrealignmentResult,
    RasterizationConfig,
    SLDDMMConfig,
    STAtlasAlignmentConfig,
    STAtlasAlignmentResult,
    UIAtlasAlignmentConfig,
    UIAtlasPairing,
    HistologyClusteringConfig,
    HistologyClusteringResult,
    HistologyFeatureConfig,
    HistologyFeatureResult,
    HistologyPrealignmentConfig,
    HistologyPrealignmentResult,
    HistologyPrealignmentUI,
    STHistologyStructureConfig,
    STHistologyAlignmentConfig,
    STHistologyAlignmentResult,
    align_st_to_histology,
    align_atac_to_st,
    build_st_histology_structures,
    align_st_to_allen_atlas,
    align_st_to_allen_atlas_from_ui_pairs,
    align_cross_sample,
    apply_similarity_transform,
    build_st_cluster_hierarchy,
    interactive_manual_prealignment,
    interactive_histology_prealignment,
    load_allen_ccf_reference,
    load_atlas_label_color_map,
    load_atlas_structure_color_map,
    load_st_atlas_alignment,
    load_ui_atlas_pairing,
    load_histology_clustering,
    load_histology_features,
    plot_atlas_label_transfer,
    plot_alignment_result,
    plot_cluster_alignment_result,
    plot_manual_prealignment_preview,
    plot_prealignment_result,
    plot_rasterized_fields,
    plot_st_atlas_alignment,
    plot_histology_feature_clusters,
    plot_histology_prealignment_preview,
    plot_st_histology_alignment,
    plot_st_histology_pair_overlap,
    plot_st_histology_structures,
    plot_atac_st_alignment,
    plot_atac_st_matched_structures,
    plot_atac_st_prealignment,
    prealign_cross_sample,
    prealign_cross_sample_manual,
    prealign_st_to_histology,
    prealign_atac_to_st,
    prepare_histology_image,
    cluster_histology_features,
    extract_histology_features,
    rasterize_cross_sample,
    run_slddmm_alignment,
)
from .io import (
    REQUIRED_OUTPUT_COLUMNS,
    load_cross_sample_data,
    load_single_sample_data,
    read_cross_sample_csv,
    read_single_sample_csv,
    validate_cross_sample_anndata,
    validate_single_sample_anndata,
)
from .clustering import JointClusteringConfig, SingleClusteringConfig
from .inference import (
    LocalDEResult,
    PreparedInference,
    TrajectoryResult,
    acat_pvalue,
    cluster_trajectories,
    fit_local_de,
    gene_level_acat_pvalue,
    plot_local_result,
    prepare_inference,
)
from .datasets import (
    AGING_BRAIN_QUERIES,
    AGING_BRAIN_REFERENCE,
    AGING_BRAIN_SAMPLES,
    KIDNEY_SAMPLES,
    VisiumInferenceInput,
    aging_brain_genes,
    aging_brain_metadata,
    build_visium_inference_table,
    canonical_visium_barcodes,
    kidney_alignment_metadata,
    load_aging_brain,
    load_kidney_aligned_coordinates,
    make_cross_sample_example,
    summarize_raw_genes,
)
from . import uncertainty
from .random import set_random_seed


def cluster_joint(
    adata: ad.AnnData,
    *,
    config: JointClusteringConfig | None = None,
    sample_key: str = "sample_id",
    spatial_key: str = "spatial",
    cluster_key: str = "cluster",
    cell_id_key: str = "cell_id",
    layer: str | None = None,
    copy: bool = True,
    return_details: bool = False,
) -> ad.AnnData | tuple[ad.AnnData, dict[str, Any]]:
    """Run the optional BANKSY/Harmony joint-clustering workflow."""
    from .clustering import cluster_joint as implementation

    return implementation(
        adata,
        config=config,
        sample_key=sample_key,
        spatial_key=spatial_key,
        cluster_key=cluster_key,
        cell_id_key=cell_id_key,
        layer=layer,
        copy=copy,
        return_details=return_details,
    )


def plot_joint_cluster_refinement(*args, **kwargs):
    """Plot raw and boundary-refined joint clusters with shared colors."""
    from .clustering import plot_joint_cluster_refinement as implementation

    return implementation(*args, **kwargs)


def cluster_single(
    adata: ad.AnnData,
    *,
    config: SingleClusteringConfig | None = None,
    spatial_key: str = "spatial",
    cluster_key: str = "cluster",
    copy: bool = True,
    banksy_output_dir: str | Path | None = None,
    return_details: bool = False,
) -> ad.AnnData | tuple[ad.AnnData, dict[str, Any]]:
    """Run the optional single-sample BANKSY clustering workflow."""
    from .clustering import cluster_single as implementation

    return implementation(
        adata,
        config=config,
        spatial_key=spatial_key,
        cluster_key=cluster_key,
        copy=copy,
        banksy_output_dir=banksy_output_dir,
        return_details=return_details,
    )


def plot_single_cluster_refinement(*args, **kwargs):
    """Plot raw and boundary-refined single-sample clusters."""
    from .clustering import plot_single_cluster_refinement as implementation

    return implementation(*args, **kwargs)


__all__ = [
    "__version__",
    "AGING_BRAIN_QUERIES",
    "AGING_BRAIN_REFERENCE",
    "AGING_BRAIN_SAMPLES",
    "ATACSTAlignmentConfig",
    "ATACSTAlignmentResult",
    "ATACSTPrealignmentConfig",
    "ATACSTPrealignmentResult",
    "AllenCCFReference",
    "CrossSampleAlignmentResult",
    "CrossSampleFields",
    "JointClusteringConfig",
    "SingleClusteringConfig",
    "ManualPrealignmentConfig",
    "ManualPrealignmentUI",
    "KIDNEY_SAMPLES",
    "LocalDEResult",
    "PrealignmentConfig",
    "PrealignmentResult",
    "PreparedInference",
    "REQUIRED_OUTPUT_COLUMNS",
    "RasterizationConfig",
    "SLDDMMConfig",
    "STAtlasAlignmentConfig",
    "STAtlasAlignmentResult",
    "UIAtlasAlignmentConfig",
    "UIAtlasPairing",
    "HistologyClusteringConfig",
    "HistologyClusteringResult",
    "HistologyFeatureConfig",
    "HistologyFeatureResult",
    "HistologyPrealignmentConfig",
    "HistologyPrealignmentResult",
    "HistologyPrealignmentUI",
    "STHistologyStructureConfig",
    "STHistologyAlignmentConfig",
    "STHistologyAlignmentResult",
    "TrajectoryResult",
    "VisiumInferenceInput",
    "aging_brain_genes",
    "aging_brain_metadata",
    "uncertainty",
    "acat_pvalue",
    "align_st_to_histology",
    "align_atac_to_st",
    "build_st_histology_structures",
    "align_st_to_allen_atlas",
    "align_st_to_allen_atlas_from_ui_pairs",
    "align_cross_sample",
    "apply_similarity_transform",
    "build_st_cluster_hierarchy",
    "build_visium_inference_table",
    "canonical_visium_barcodes",
    "interactive_manual_prealignment",
    "interactive_histology_prealignment",
    "load_allen_ccf_reference",
    "load_atlas_label_color_map",
    "load_atlas_structure_color_map",
    "load_st_atlas_alignment",
    "load_ui_atlas_pairing",
    "load_histology_clustering",
    "load_histology_features",
    "load_aging_brain",
    "load_kidney_aligned_coordinates",
    "make_cross_sample_example",
    "summarize_raw_genes",
    "cluster_joint",
    "cluster_single",
    "cluster_trajectories",
    "fit_local_de",
    "gene_level_acat_pvalue",
    "load_cross_sample_data",
    "load_single_sample_data",
    "plot_alignment_result",
    "plot_atlas_label_transfer",
    "plot_cluster_alignment_result",
    "plot_manual_prealignment_preview",
    "plot_local_result",
    "plot_joint_cluster_refinement",
    "plot_single_cluster_refinement",
    "plot_prealignment_result",
    "plot_rasterized_fields",
    "plot_st_atlas_alignment",
    "plot_histology_feature_clusters",
    "plot_histology_prealignment_preview",
    "plot_st_histology_alignment",
    "plot_st_histology_pair_overlap",
    "plot_st_histology_structures",
    "plot_atac_st_alignment",
    "plot_atac_st_matched_structures",
    "plot_atac_st_prealignment",
    "prealign_cross_sample",
    "prealign_cross_sample_manual",
    "prealign_st_to_histology",
    "prealign_atac_to_st",
    "prepare_inference",
    "kidney_alignment_metadata",
    "prepare_histology_image",
    "cluster_histology_features",
    "extract_histology_features",
    "rasterize_cross_sample",
    "read_cross_sample_csv",
    "read_single_sample_csv",
    "run_slddmm_alignment",
    "set_random_seed",
    "validate_cross_sample_anndata",
    "validate_single_sample_anndata",
]
